name: Check and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain
        run: |
          rustup install nightly
          rustup component add rustfmt --toolchain nightly
          rustup show
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: check-and-test-ubuntu-latest-v1
      - name: Check code format
        run: cargo +nightly fmt -- --check
      - name: Check the package for errors
        run: cargo check --all
      - name: Lint rust sources
        run: cargo clippy --all-targets --all-features -- -D warnings
